apiVersion: v1
kind: ConfigMap
metadata:
  name: task3-config
data:
  DATABASE_HOST: postgres
  DATABASE_USER: myuser
  DATABASE_DB: myapp
---
apiVersion: v1
kind: Secret
metadata:
  name: task3-secret
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dk